### ISSUE TITLE
Default destination doesn't work 

### ISSUE THREAD

**Issue by bkolada** [matthistuff/kepuber#1]
Hi,
It looks like if I don't set up '-d parameter then output files aren't saved in current folder. I looked for created files with pattern '*kepub.epub' on root folder but there weren't any results so I'm not sure what's going on with that. 

I worked on version 0.0.6 from npm on fedora 21. 
_edit_
I just checked if following command works 'kepuber some.epub -d . ' but that also doesn't work and I have to provide absolute path.

**Comment by matthistuff** [comment]
Hi @bkolada, thank you for reporting! I will investigate but it will probably take me a few days depending on how much spare time I can find.

**Comment by matthistuff** [comment]
Hi @bkolada, I fixed the `kepuber some.epub -d .` part. When omitting the `-d` argument, the `*.kepub.epub` will be created in the same folder as the source file.

**Comment by bkolada** [comment]
Hey @matthistuff thanks for fixing and I've just updated kepuber but it looks like without `-d` it still doesn't work, but `-d .` works great. For me it's enough. 

Thanks for helping.
